version: '3.8'

services:
  web-app:
    container_name: golang
    build: .
    ports:
      - 5050:5050
    volumes:
      - .:/go-backend
    depends_on:
      - db
    restart: always
  

  db:
    image: postgres 
    container_name: db
    environment:
      - POSTGRES_DB=Go-Backend-Coffee-Shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - 5111:5432